[package]
name = "squib-virtio"
description = "virtio-MMIO transport and per-device drivers for squib"
categories = ["virtualization"]
keywords = ["virtio", "mmio", "block", "net", "vsock"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
squib-arch = { workspace = true }
squib-bus = { workspace = true }
squib-core = { workspace = true }
squib-gic = { workspace = true }
squib-mmds = { workspace = true }

bytes = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
